-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/kvimcrew/kvim/blob/main/lua/kvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `kvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name(kvim_wrap_spell")
