-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/kvimcrew/kvim/blob/main/lua/kvim/config/options.lua
-- Add any additional options here
